### ISSUE TITLE
Add $()N? attribute syntax.

### ISSUE THREAD

**Issue by s3rius** [wierd-stuff-inc/scribes#2]
Add syntax for "Maybe match" cases with default values.
Use case: 
Needs to define color in your plugin but if no color defined needs to use black. You add `(.*)?` in your match pattern, and `$('black')2?` in your attrs. then if the second match group was not found - your plugin will use black instead.

**Comment by s3rius** [comment]
@Kolaer, @ussr-jesus  any ideas?

**Comment by Kolaer** [comment]
I think there would be a few problems with current approach:
* Only one optional parameter.
* Optional parameter must be last.

So I think we have two options: redesign parameters, or skip this feature.
Or I'm missing something very obvious.

**Comment by s3rius** [comment]
Yeah, i guess we better course this issue, because i don't have clear solution for that.
We'll discuss about it later.

**Comment by s3rius** [comment]
Yeah, i guess we better close this issue, because i don't have clear solution for that.
We'll discuss about it later.
